=== Sergi-FR/Projecte2/Web/xml/curses.dtd
<!ELEMENT curses (cursa+)>
<!ELEMENT cursa (nom, modalitat, localitat, durada, data, img)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT modalitat (#PCDATA)>
<!ELEMENT localitat (#PCDATA)>
<!ELEMENT durada (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT img (#PCDATA)>


<!ATTLIST cursa id ID #REQUIRED>

=== Sergi-FR/Projecte2/Web/xml/curses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curses SYSTEM "curses.dtd">
<?xml-stylesheet type="text/xsl" href="curses.xsl"?>
<curses>
  <cursa id="b4">
    <nom>Bicicleta castells</nom>
    <modalitat>Bicicleta</modalitat>
    <localitat>Cervera</localitat>
    <durada>12km</durada>
    <data>25-04-2022</data>
    <img>id_1.jpg</img>
  </cursa>
  
  <cursa id="c2">
    <nom>Mitja Marato</nom>
    <modalitat>Correr</modalitat>
    <localitat>Tarrega</localitat>
    <durada>3km</durada>
    <data>16-03-2022</data>
    <img>id_2.jpg</img>
  </cursa>
  
  <cursa id="t1">
    <nom>Duatlón 22</nom>
    <modalitat>Triatló</modalitat>
    <localitat>Ponts</localitat>
    <durada>20km</durada>
    <data>5-07-2022</data>
    <img>id_3.jpg</img>
  </cursa> 
</curses>
